module.exports = {
  up: async (queryInterface) => queryInterface.bulkInsert(
    'bikes',
    [
      {
        id: 1,
        model: 'Bike 1',
        color: 'red',
        location: 'Location 1',
        rating: 4.5,
        image: '/images/1/main.jpeg',
        price: 10.00,
      },
      {
        id: 2,
        model: 'Bike 2',
        color: 'blue',
        location: 'Location 2',
        rating: 4.5,
        image: '/images/2/main.jpeg',
        price: 10.00,
      },
      {
        id: 3,
        model: 'Bike 3',
        color: 'green',
        location: 'Location 3',
        rating: 4.5,
        image: '/images/3/main.jpeg',
        price: 10.00,
      },
      {
        id: 4,
        model: 'Bike 4',
        color: 'yellow',
        location: 'Location 4',
        rating: 4.5,
        image: '/images/4/main.jpeg',
        price: 10.00,
      },
      {
        id: 5,
        model: 'Bike 5',
        color: 'orange',
        location: 'Location 5',
        rating: 4.5,
        image: '/images/5/main.jpeg',
        price: 10.00,
      },
      {
        id: 6,
        model: 'Bike 6',
        color: 'purple',
        location: 'Location 6',
        rating: 4.5,
        image: '/images/6/main.jpeg',
        price: 10.00,
      },
    ],

    {},
  ),

  down: async (queryInterface) => queryInterface.bulkDelete('users', null, {}),
};
