module.exports = {
  up: async (queryInterface) => queryInterface.bulkInsert(
    'cars',
    [
      {
        id: 1,
        model_id: 1,
        color_id: 1,
        location_id: 1,
        image: '/images/cars/1/main.jpeg',
        price: 10,
        rating: 0,
        received_rates: 0,
      },
      {
        id: 2,
        model_id: 1,
        color_id: 2,
        location_id: 1,
        image: '/images/cars/2/main.jpeg',
        price: 10,
        rating: 5,
        received_rates: 1,
      },
      {
        id: 3,
        model_id: 1,
        color_id: 3,
        location_id: 1,
        image: '/images/cars/3/main.jpeg',
        price: 10,
        rating: 4.5,
        received_rates: 2,
      },
      {
        id: 4,
        model_id: 2,
        color_id: 1,
        location_id: 1,
        image: '/images/cars/4/main.jpeg',
        price: 10,
        rating: 4,
        received_rates: 3,
      },
      {
        id: 5,
        model_id: 2,
        color_id: 1,
        location_id: 2,
        image: '/images/cars/5/main.jpeg',
        price: 10,
        rating: 3.5,
        received_rates: 4,
      },
      {
        id: 6,
        model_id: 2,
        color_id: 2,
        location_id: 2,
        image: '/images/cars/6/main.jpeg',
        price: 10,
        rating: 0,
        received_rates: 0,
      },
    ],

    {},
  ),

  down: async (queryInterface) => queryInterface.bulkDelete('cars', null, {}),
};
